spring.application.name=Routing_Ev

spring.datasource.url=jdbc:postgresql://localhost:5432/ev_routing
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Création automatique des tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Activer PostGIS
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

openchargemap.api.key=${OPENCHARGEMAP_API_KEY}